name: Deploy to PythonAnywhere

on:
  push:
    branches:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deployment webhook
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "X-Hub-Signature-256: $(echo -n '{"ref": "refs/heads/main"}' | openssl dgst -sha256 -hmac ${{ secrets.GITHUB_SECRET }} | sed 's/^.* //')" \
        -d '{"ref": "refs/heads/main"}' \
        https://yourapp.pythonanywhere.com/webhook
